//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCard
    {
        public int CodeCardWork { get; set; }
        public int CodeProduct { get; set; }
        public int CodePost { get; set; }
        public int CodeOperation { get; set; }
        public int OperatonOrder { get; set; }
        public int ElapsedTime { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Post Post { get; set; }
        public virtual Product Product { get; set; }
    }
}
