//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatinumInform.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RatepInformEntities : DbContext
    {
        public RatepInformEntities()
            : base("name=RatepInformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<JobCard> JobCard { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialCard> MaterialCard { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
