//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatinumInform.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCard
    {
        public int NumMatCard { get; set; }
        public int CodeMaterial { get; set; }
        public int CodeProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
